GET http://localhost:5015/games

###
GET http://localhost:5015/games/4

###
Post http://localhost:5015/games/
Content-Type: application/json

{
    "name": "MarioKart 8",
    "genreId": 5,
    "Price": 69.99,
    "releaseDate": "2025-06-21"
}

###
PUT http://localhost:5015/games/4
Content-Type: application/json

{
  "name": "MarioKart 10",
  "genreId": 1,
  "price": 59.99,
  "releaseDate": "2014-05-30"
}

###
DELETE http://localhost:5015/games/4
Content-Type: application/json

{
  "id": 4,
  "name": "MarioKart 8",
  "genre": "Racing",
  "price": 59.99,
  "releaseDate": "2014-05-30"
}